auto_save: 'no'
background_color: ''
chain_cursors: 'no'
clinical_mode: 'yes'
name: MIA2
nb_slices_max: '10'
opened_projects: []
show_all_slices: 'no'
text_color: ''
thumbnail_tag: SequenceName
use_matlab: 'no'
use_spm: 'no'
use_spm_standalone: 'no'
